### ISSUE TITLE
Galah not on CRAN?

### ISSUE THREAD

**Issue by wcornwell** [AtlasOfLivingAustralia/galah-R#197]
**Describe the bug**
<img width="598" alt="Screenshot 2023-06-09 at 10 20 46 am" src="https://github.com/AtlasOfLivingAustralia/galah-R/assets/5534161/d88ffbe2-14af-460a-aac2-f4d060503604">

**Additional context**
Not really an issue for me personally, but for teaching it makes it a bit more awkward to get `galah` installed on a lot of machines.

**Comment by daxkellie** [comment]
Hi Will,
Thanks for reaching out. {galah} was taken off CRAN a little while ago due to a minor API issue (which is now fixed), but we were midway through a few more exciting changes that we wanted to implement before resubmitting {galah} to CRAN.

We are working hard to get the next release out (version 1.6) and will hopefully have it {galah} back up in the coming weeks!

**Comment by daxkellie** [comment]
Just wanted to note that galah 1.5.3 is now on CRAN! 😃

**Comment by wcornwell** [comment]
excellent!
