### ISSUE TITLE
`collect_media()` returns an error using the example in the documentation

### ISSUE THREAD

**Issue by shandiya** [AtlasOfLivingAustralia/galah-R#243]
When running the example listed in the function documentation for `collect_media()`, the following error is returned:
`Error in missing(fail) : 'missing' can only be used for arguments`
The media appear to download into the specified directory regardless, but the error is confusing. 

**galah version**
 2.0.0

**Comment by daxkellie** [comment]
Thanks for this. I tried running the example on my computer using galah 2.0.2 and it worked for me, so I wasn't able to replicate the error.

Would you mind updating to the latest version of (galah 2.0.2) and trying this example again? There have been a few bug fixes to media downloads in the minor releases since version 2.0.0, so fingers crossed updating fixes the issue for you too.

**Comment by shandiya** [comment]
Thanks! Updating to 2.02 has fixed the error :)
