### ISSUE TITLE
Add instructions for how to refresh the cache

### ISSUE THREAD

**Issue by matildastevenson** [AtlasOfLivingAustralia/galah-R#65]
Possibly in a caching vignette, or in the main vignette

**Comment by daxkellie** [comment]
Caching was removed in previous version due to increasingly difficult problems integrating with upgrades that eventually led to a new query architecture in galah 2.0.0. However, galah 2.0.0 is much faster that previous versions and allows the ability to send queries on the server-side without holding up the R terminal 🥳 

Closing for now while caching is no longer supported
